name: Carz
version: "7.0"
description: Drive in Minecraft
softdepend: [Vault, BountifulAPI]
author: A5H73Y
main: io.github.a5h73y.Carz
api-version: "1.13"
commands:
  carz:
    description: Carz commands
  carzc:
    description: Carz non-player commands
