name: Carz
version: ${project.version}
description: ${project.description}
softdepend: [Vault, BountifulAPI, PlaceholderAPI]
author: A5H73Y
main: io.github.a5h73y.carz.Carz
api-version: "1.13"
website: "https://a5h73y.github.io/Carz/"
commands:
  carz:
    description: Carz commands
  carzc:
    description: Carz non-player commands
